### ISSUE TITLE
ES6 Syntax not being transpiled in .es.js

### ISSUE THREAD

**Issue by chrisboustead** [brightcove/videojs-errors#124] opened 2018-07-16 14:54 UTC
## Description
v4.1.1 is not transpiling es6 syntax correctly.  Specifically, arrow functions are not being transpiled.  Not an issue in v4.1.0

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. `git clone git@github.com:brightcove/videojs-errors.git`
2. `cd videojs-errors`
3. `npm i`
4. `npm run build`
5. `grep "=>" ./dist/videojs-errors.es.js`
6. Observe that there are remaining arrow functions.

7. `git fetch --all --tags --prune`
8. `git checkout tags/v4.1.0 -b v410`
9. `npm i`
10. `npm build`
5. `grep "=>" ./dist/videojs-errors.es.js`
6. Observe that there no are remaining arrow functions.

### Expected
Expected to see es5 friendly syntax. 

### Actual
Expected to see es6 syntax, specifically arrow functions.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
`^6.8.0 || ^7.0.0`

#### browsers
what browser are affected?
cli only.

#### OSes
what platforms (operating systems and devices) are affected?
OSX 10.13.3

### plugins
are any videojs plugins being used on the page? If so, please list them below.
No.

**Comment by BrandonOCasey** [comment] 2018-07-16 15:01
We are working on a fix for this, it was caused by an update to the generator and my incorrect assumptions. Sorry about that

**Comment by chrisboustead** [comment] 2018-07-16 15:16
Thanks! I submitted a PR which fixes this specific issue, but by the looks of how extensive the changes were between 4.1.0 and 4.1.1, there is potentially more which needs to be addressed.

**Closed** 2018-08-03 17:20 UTC
